Revert from send('eth_requestAccounts') to window.ethereum.enable()
This is because metamask blows up with 'TypeErrore is not a function' whenever user denies privacy access to Metamask. I also add error message into console.log and remove meaningless throw which get caught again in the outter loop.